#!/bin/bash

echo "🚀 MotoGarage Production Deployment Script"
echo "=========================================="

# FTP Bilgileri
FTP_HOST="195.35.49.18"
FTP_USER="u456124799.minigaraj.store"
FTP_PORT="21"
UPLOAD_DIR="public_html"

echo "📋 Deployment Adımları:"
echo "1. Frontend build dosyaları hazırlanıyor..."
echo "2. Backend JAR dosyası hazırlanıyor..."
echo "3. Konfigürasyon dosyaları hazırlanıyor..."
echo "4. FTP ile dosya yükleme talimatları..."

echo ""
echo "📁 Yüklenecek Dosyalar:"
echo "- frontend-build/ → $UPLOAD_DIR/"
echo "- backend.jar → $UPLOAD_DIR/backend/"
echo "- application-prod.properties → $UPLOAD_DIR/backend/"
echo "- start-backend.sh → $UPLOAD_DIR/backend/"
echo "- nginx.conf → sunucu root dizinine"

echo ""
echo "🔧 Sunucu Kurulum Komutları:"
echo "sudo apt update"
echo "sudo apt install postgresql postgresql-contrib openjdk-17-jdk nginx"
echo "sudo systemctl start postgresql"
echo "sudo systemctl enable postgresql"

echo ""
echo "🗄️ Veritabanı Kurulumu:"
echo "sudo -u postgres psql"
echo "CREATE DATABASE motogarage;"
echo "CREATE USER motogarage_user WITH PASSWORD 'your_secure_password';"
echo "GRANT ALL PRIVILEGES ON DATABASE motogarage TO motogarage_user;"
echo "\\q"

echo ""
echo "🌐 Nginx Konfigürasyonu:"
echo "sudo cp nginx.conf /etc/nginx/sites-available/minigaraj.store"
echo "sudo ln -s /etc/nginx/sites-available/minigaraj.store /etc/nginx/sites-enabled/"
echo "sudo nginx -t"
echo "sudo systemctl reload nginx"

echo ""
echo "⚙️ Backend Servis Kurulumu:"
echo "sudo systemctl enable motogarage-backend"
echo "sudo systemctl start motogarage-backend"

echo ""
echo "✅ Deployment tamamlandığında test edin:"
echo "curl http://minigaraj.store/api/stock"
echo "curl http://minigaraj.store/health"

echo ""
echo "📖 Detaylı rehber için: DEPLOYMENT_GUIDE.md dosyasını inceleyin"
echo ""
echo "🎯 FTP Bilgileri:"
echo "Host: $FTP_HOST"
echo "User: $FTP_USER"
echo "Port: $FTP_PORT"
echo "Directory: $UPLOAD_DIR"
