version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: motogarage
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    build: ./backend
    environment:
      SPRING_DATASOURCE_URL: ${DATABASE_URL:-jdbc:postgresql://db:5432/motogarage}
      SPRING_PROFILES_ACTIVE: production
      SERVER_PORT: ${PORT:-8080}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${PORT:-8080}:${PORT:-8080}"

  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL:-http://localhost:8080/api}
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
